version: "3"
services:
  strapi:
    container_name: strapi
    image: strapi/strapi
    command: sh -c "yarn install && yarn build && yarn start"
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_HOST: postgres
    #   DATABASE_PORT: 5432
    #   DATABASE_NAME: strapi-parus-smart
    #   DATABASE_USERNAME: postgres
    #   DATABASE_PASSWORD: postgres
    #   DATABASE_SCHEMA: public
    volumes:
      - ./app:/srv/app
    ports:
      - "1338:1337"
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: strapi-parus-smart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
